### ISSUE TITLE
crash in client.go

### ISSUE THREAD

**Issue by catalinii** [yookoala/gofast#74]
The gofast is setup to interact with the php7.4-fpm and I get the crash of the app with the following log messages:
2021/09/22 11:24:31 gofast: error writing error buffer to response: gofast: copy error: write tcp 10.0.255.150:443->54.36.148.120:37375: write: connection reset by peer
2021/09/22 11:24:31 gofast: error stream from application process gofast: timeout or canceled
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2939d4]

goroutine 72774 [running]:
github.com/yookoala/gofast.(*client).readResponse.func1(0x400051e000, 0x40003fa440, 0x40001a4a80, 0x400007aae0)
        /root/go/pkg/mod/github.com/yookoala/gofast@v0.6.0/client.go:213 +0x24
created by github.com/yookoala/gofast.(*client).readResponse
        /root/go/pkg/mod/github.com/yookoala/gofast@v0.6.0/client.go:210 +0x84
exit status 2

**Comment by yookoala** [comment]
Can you show more of your code?

It's hard to tell what happened without further information.

**Comment by catalinii** [comment]
`
func forum(w http.ResponseWriter, r *http.Request) {
        log.Printf("php %v %v", r.RemoteAddr, r.URL.Path)
        cgi.ServeHTTP(w, r)
}

func main() {
        connFactory := gofast.SimpleConnFactory("unix", "/run/php/php7.4-fpm.sock")
        ssl := http.NewServeMux()

        // handles static assets in the assets folder
        file = http.FileServer(http.FileSystem(http.Dir(DOC_ROOT)))
        ssl.HandleFunc("/forum/", forum)
        cgi = gofast.NewHandler(
                gofast.NewPHPFS(DOC_ROOT)(gofast.BasicSession),
                gofast.SimpleClientFactory(connFactory),
        )
        cfg := &tls.Config{
                MinVersion:               tls.VersionTLS12,
                CurvePreferences:         []tls.CurveID{tls.CurveP521, tls.CurveP384, tls.CurveP256},
                PreferServerCipherSuites: true,
                CipherSuites: []uint16{
                        tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
                },
        }
        srv := &http.Server{
                Addr:         ":443",
                Handler:      ssl,
                TLSConfig:    cfg,
                TLSNextProto: make(map[string]func(*http.Server, *tls.Conn, http.Handler), 0),
        }
       
        // serve at ssl port
        log.Fatal(srv.ListenAndServeTLS("fullchain.pem", "privkey.pem"))`

Forgot to mention, this happens after running for multiple hours.

**Comment by yookoala** [comment]
Thanks. Will check this issue.
